-- 1. pizza_types
CREATE TABLE pizza_types (
    pizza_type_id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    ingredients TEXT NOT NULL
);

-- 2. pizzas
CREATE TABLE pizzas (
    pizza_id VARCHAR(50) PRIMARY KEY,
    pizza_type_id VARCHAR(50) NOT NULL REFERENCES pizza_types(pizza_type_id) ON UPDATE CASCADE,
    size VARCHAR(5) NOT NULL,
    price NUMERIC(6,2) NOT NULL CHECK (price > 0)
);

-- 3. orders
CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    date DATE NOT NULL,
    time TIME NOT NULL
);

-- 4. order_details
CREATE TABLE order_details (
    order_details_id INT PRIMARY KEY,
    order_id INT NOT NULL REFERENCES orders(order_id) ON UPDATE CASCADE ON DELETE CASCADE,
    pizza_id VARCHAR(50) NOT NULL REFERENCES pizzas(pizza_id) ON UPDATE CASCADE,
    quantity INT NOT NULL CHECK (quantity > 0)
);

SELECT * FROM pizza_types;
SELECT * FROM pizzas;
SELECT * FROM orders;
SELECT * FROM order_details;


-- Intermediate Query

-- 1. Join the necessary tables to find the total quantity of each pizza category ordered

SELECT 
    pt.category,
    SUM(od.quantity) AS total_quantity_ordered
FROM pizza_types pt
JOIN pizzas p ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od ON od.pizza_id = p.pizza_id
GROUP BY pt.category
ORDER BY total_quantity_ordered DESC;

-- 2. Determine the distribution of orders by hour of the day

SELECT 
    EXTRACT(HOUR FROM time) AS order_hour,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY EXTRACT(HOUR FROM time)
ORDER BY total_orders DESC;

-- 3. Join relevant tables to find the category-wise distribution of pizzas

SELECT 
    category,
    COUNT(pizza_type_id) AS pizza_count
FROM pizza_types
GROUP BY category
ORDER BY pizza_count DESC;


-- 4. Group the orders by date and calculate the average number of pizzas ordered per day

SELECT 
    ROUND(AVG(daily_pizzas), 0) AS avg_pizzas_per_day
FROM (
    SELECT 
        o.date,
        SUM(od.quantity) AS daily_pizzas
    FROM orders o
    JOIN order_details od ON o.order_id = od.order_id
    GROUP BY o.date
) AS daily_sales;

-- 5. Determine the top 3 most ordered pizza types based on revenue

SELECT 
    pt.name,
    ROUND(SUM(od.quantity * p.price)::NUMERIC, 2) AS total_revenue
FROM pizza_types pt
JOIN pizzas p ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od ON od.pizza_id = p.pizza_id
GROUP BY pt.name
ORDER BY total_revenue DESC
LIMIT 3;

-- 6. Find the total revenue generated by each pizza category

SELECT 
    pt.category,
    ROUND(SUM(od.quantity * p.price)::NUMERIC, 2) AS total_revenue
FROM pizza_types pt
JOIN pizzas p ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od ON od.pizza_id = p.pizza_id
GROUP BY pt.category
ORDER BY total_revenue DESC;

-- 7. Compare total revenue generated across all pizza sizes

SELECT 
    p.size,
    SUM(od.quantity) AS total_quantity_sold,
    ROUND(SUM(od.quantity * p.price)::NUMERIC, 2) AS total_revenue
FROM pizzas p
JOIN order_details od ON p.pizza_id = od.pizza_id
GROUP BY p.size
ORDER BY total_revenue DESC;

-- 8. Identify orders where a customer bought 3 or more units of the exact same pizza

SELECT 
    od.order_id,
    pt.name,
    p.size,
    od.quantity
FROM order_details od
JOIN pizzas p ON od.pizza_id = p.pizza_id
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
WHERE od.quantity >= 3
ORDER BY od.quantity DESC, od.order_id;

-- 9. Compare total order volume and revenue: Weekdays vs. Weekends

SELECT 
    CASE 
        WHEN EXTRACT(DOW FROM o.date) IN (0, 6) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_classification,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(SUM(od.quantity * p.price)::NUMERIC, 2) AS total_revenue
FROM orders o
JOIN order_details od ON o.order_id = od.order_id
JOIN pizzas p ON od.pizza_id = p.pizza_id
GROUP BY 1;

-- 10. Find the top 3 best-selling pizzas for every individual size (S, M, L)

WITH ranked_sizes AS (
    SELECT 
        p.size,
        pt.name,
        SUM(od.quantity) AS total_sold,
        DENSE_RANK() OVER (
            PARTITION BY p.size 
            ORDER BY SUM(od.quantity) DESC
        ) AS size_rank
    FROM order_details od
    JOIN pizzas p ON od.pizza_id = p.pizza_id
    JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
    WHERE p.size IN ('S', 'M', 'L')
    GROUP BY p.size, pt.name
)
SELECT size, size_rank, name, total_sold
FROM ranked_sizes
WHERE size_rank <= 3
ORDER BY size, size_rank;

-- 11. Find orders containing both a Chicken pizza and a Veggie pizza in the same basket

SELECT od.order_id
FROM order_details od
JOIN pizzas p ON od.pizza_id = p.pizza_id
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
GROUP BY od.order_id
HAVING 
    COUNT(DISTINCT CASE WHEN pt.category = 'Chicken' THEN pt.category END) > 0
    AND 
    COUNT(DISTINCT CASE WHEN pt.category = 'Veggie' THEN pt.category END) > 0;


-- 12. Calculate the percentage of orders placed during each 3-hour time block

SELECT 
    CASE 
        WHEN EXTRACT(HOUR FROM time) BETWEEN 9 AND 11 THEN '09:00 - 11:59 (Morning)'
        WHEN EXTRACT(HOUR FROM time) BETWEEN 12 AND 14 THEN '12:00 - 14:59 (Lunch)'
        WHEN EXTRACT(HOUR FROM time) BETWEEN 15 AND 17 THEN '15:00 - 17:59 (Afternoon)'
        WHEN EXTRACT(HOUR FROM time) BETWEEN 18 AND 20 THEN '18:00 - 20:59 (Dinner)'
        ELSE '21:00+ (Late Night)'
    END AS time_block,
    COUNT(order_id) AS total_orders,
    ROUND((COUNT(order_id)::NUMERIC / SUM(COUNT(order_id)) OVER () * 100)::NUMERIC, 2) AS order_percentage
FROM orders
GROUP BY 1
ORDER BY total_orders DESC;


-- 13. Find pairs of pizzas that are most frequently ordered together in the same order

SELECT 
    od1.pizza_id AS item_a,
    od2.pizza_id AS item_b,
    COUNT(*) AS times_bought_together
FROM order_details od1
JOIN order_details od2 
    ON od1.order_id = od2.order_id 
   AND od1.pizza_id < od2.pizza_id
GROUP BY od1.pizza_id, od2.pizza_id
ORDER BY times_bought_together DESC
LIMIT 5;

-- 14. Find the busiest day in terms of revenue for each month

WITH daily_revenue AS (
    SELECT 
        o.date,
        TO_CHAR(o.date, 'YYYY-MM') AS month_year,
        SUM(od.quantity * p.price) AS total_revenue,
        ROW_NUMBER() OVER (
            PARTITION BY TO_CHAR(o.date, 'YYYY-MM') 
            ORDER BY SUM(od.quantity * p.price) DESC
        ) AS rank_in_month
    FROM orders o
    JOIN order_details od ON o.order_id = od.order_id
    JOIN pizzas p ON od.pizza_id = p.pizza_id
    GROUP BY o.date
)
SELECT month_year, date, ROUND(total_revenue::NUMERIC, 2) AS peak_day_revenue
FROM daily_revenue
WHERE rank_in_month = 1
ORDER BY month_year;

-- 15. Find all pizzas that were ordered fewer than 1,000 times overall

SELECT 
    pt.name,
    SUM(od.quantity) AS total_sold
FROM pizza_types pt
JOIN pizzas p ON pt.pizza_type_id = p.pizza_type_id
JOIN order_details od ON p.pizza_id = od.pizza_id
GROUP BY pt.name
HAVING SUM(od.quantity) < 1000
ORDER BY total_sold ASC;

-- 16. Find pizzas priced higher than the average price of their respective category

WITH category_averages AS (
    SELECT 
        pt.category,
        AVG(p.price) AS avg_cat_price
    FROM pizzas p
    JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
    GROUP BY pt.category
)
SELECT 
    pt.name,
    pt.category,
    p.size,
    p.price,
    ROUND(ca.avg_cat_price::NUMERIC, 2) AS category_avg_price
FROM pizzas p
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
JOIN category_averages ca ON pt.category = ca.category
WHERE p.price > ca.avg_cat_price
ORDER BY pt.category, p.price DESC;


-- 17. Identify the most popular pizza size for each pizza category

WITH size_popularity AS (
    SELECT 
        pt.category,
        p.size,
        SUM(od.quantity) AS total_sold,
        RANK() OVER (
            PARTITION BY pt.category 
            ORDER BY SUM(od.quantity) DESC
        ) AS rank_in_cat
    FROM order_details od
    JOIN pizzas p ON od.pizza_id = p.pizza_id
    JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
    GROUP BY pt.category, p.size
)
SELECT category, size, total_sold
FROM size_popularity
WHERE rank_in_cat = 1
ORDER BY total_sold DESC;